### ISSUE TITLE
Equal condition query for uint8 column returns always no result.

### ISSUE THREAD

**Issue by genki** [groonga/groonga#1437] opened 2022-10-29 23:16 UTC
Here's my environment:
```
groonga --version
Groonga 8.1.0 [linux-gnu,x86_64,utf8,match-escalation-threshold=0,nfkc,mecab,mruby,onigmo,zlib,epoll]

configure options: < '--prefix=/usr' '--enable-mruby' '--with-ruby' 'CFLAGS=--param max-gcse-memory=268435456'
```

Command below returns always empty:
`select <Table> --query <uint8-column>:<value>`

Same command for uint32 column gets succeeded.
Command below works as expected:
`select <Table> --query <uint8-column>:><value>`

I guess there may be a bug especially in treatment of uint8 column.

Because I have no newer versions of Groonga for now, so this issue might have been solved already, though.

**Comment by komainu8** [comment] 2022-10-31 05:13
Thank you for your report.
However, I can't reproduce this problem in my environment as below.

```
$ groonga --version
Groonga 8.1.0 [linux-gnu,x86_64,utf8,match-escalation-threshold=0,nfkc,mecab,msgpack,mruby,onigmo,zlib,lz4,zstd,epoll]

configure options: < '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--disable-static' '--with-package-platform=centos7' '--with-mecab' '--with-munin-plugins' '--enable-mruby' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro ' 'CXXFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig'>

$ groonga -n db/db
> status
[[0,1667187545.394979,0.0007488727569580078],{"alloc_count":16524,"starttime":1667187529,"start_time":1667187529,"uptime":16,"version":"8.1.0","n_queries":0,"cache_hit_rate":0.0,"command_version":1,"default_command_version":1,"max_command_version":3}]
> 
> table_create Entries TABLE_PAT_KEY ShortText
[[0,1667187547.414153,0.01349043846130371],true]
> column_create Entries content COLUMN_SCALAR Text
[[0,1667187547.428306,0.0032958984375],true]
> column_create Entries n_likes COLUMN_SCALAR UInt8
[[0,1667187547.431772,0.001382350921630859],true]
> 
> load --table Entries
> [
> {"_key":    "The first post!",
>  "content": "Welcome! This is my first post!",
>  "n_likes": 5},
> {"_key":    "Groonga",
>  "content": "I started to use Groonga. It's very fast!",
>  "n_likes": 10},
> {"_key":    "Mroonga",
>  "content": "I also started to use Mroonga. It's also very fast! Really fast!",
>  "n_likes": 15},
> {"_key":    "Good-bye Senna",
>  "content": "I migrated all Senna system!",
>  "n_likes": 3},
> {"_key":    "Good-bye Tritonn",
>  "content": "I also migrated all Tritonn system!",
>  "n_likes": 3}
> ]
[[0,1667187547.433238,0.003948450088500977],5]
> 
> select --table Entries --query n_likes:10
[[0,1667187547.438649,0.0006196498870849609],[[[1],[["_id","UInt32"],["_key","ShortText"],["content","Text"],["n_likes","UInt8"]],[2,"Groonga","I started to use Groonga. It's very fast!",10]]]]
```

Could you provide schema and query when this problem reproduces?

**Comment by genki** [comment] 2022-10-31 08:09
Thank you for testing. I too couldn't reproduce the issue from your example.
Here's dump that causes the issue:

```
table_create Media TABLE_HASH_KEY ShortText
column_create Media ctime COLUMN_SCALAR UInt32
column_create Media desc COLUMN_SCALAR|COMPRESS_ZSTD Text
column_create Media type COLUMN_SCALAR UInt8

table_create MediaTerms TABLE_PAT_KEY ShortText --default_tokenizer TokenBigram

load --table Media
[
["_key","ctime","desc","type"],
["1586508073753268224",1667087975,"ａ ｔｒａｉｎ ｉｎ ｓｉｎｇａｐｏｒｅ ｗｉｔ>ｈ ｗｉｎｄｏｗｓ ｔｈａｔ ａｕｔｏｍａｔｉｃａｌｌｙ ｂｌｉｎｄ ｗｈｅｎ ｐａｓ
ｓｉｎｇ ｒｅｓｉｄｅｎｔｉａｌ ｂｌｏｃｋｓ． ｈｔｔｐｓ：／／ｔ．ｃｏ／ｓ０ｍ>ｋｐｆｄｄｐｉ",4],
["1586906813626486785",1667183042,"どうもヨコヅナ研究家のまんぷくです。 以前のツ
イートでも紹介しましたがバクダンの爆風に捲き込むだけでこんなに大ダメージ入ります
。 今回は２体同時だったのでわかりやすいと思います！ 参考にしてください。 ＃サー>モンラン ＃スプラトゥーン３ ＃ｓｐｌａｔｏｏｎ３ ＃ｎｉｎｔｅｎｄｏｓｗｉｔｃｈ ＃ｒｔ拡散希望 ｈｔｔｐｓ：／／ｔ．ｃｏ／ｒｃｔｓｔｌｋｅｎｃ",4],
["1586957457896591360",1667195116,"ブルボンメタバース ｈｔｔｐｓ：／／ｔ．ｃｏ／
ｔｒｒｔｖｔｌｂｗ９",4]
]

column_create MediaTerms Media_desc COLUMN_INDEX|WITH_POSITION Media desc
column_create MediaTerms Media_type COLUMN_INDEX|WITH_POSITION Media type
```

And then, '>=' can select correct records but ':' can't as follows:

```
> select Media --query type:>=4
[[0,1667203596.492417,0.2479186058044434],[[[3],[["_id","UInt32"],["_key","ShortText"],["ctime","UInt32"],["desc","Text"],["type","UInt8"]],[1,"1586508073753268224",1667087975,"ａ ｔｒａｉｎ ｉｎ ｓｉｎｇａｐｏｒｅ ｗｉｔｈ ｗｉｎｄｏｗｓ 
  ｈａｔ ａｕｔｏｍａｔｉｃａｌｌｙ ｂｌｉｎｄ ｗｈｅｎ ｐａｓｓｉｎｇ ｒｅｓｉ
  ｅｎｔｉａｌ ｂｌｏｃｋｓ． ｈｔｔｐｓ：／／ｔ．ｃｏ／ｓ０ｍｋｐｆｄｄｐｉ",4],[2,"1586906813626486785",1667183042,"どうもヨコヅナ研究家のまんぷくです。 以前
  ツイートでも紹介しましたがバクダンの爆風に捲き込むだけでこんなに大ダメージ入り
  す。 今回は２体同時だったのでわかりやすいと思います！ 参考にしてください。 ＃
  ーモンラン ＃スプラトゥーン３ ＃ｓｐｌａｔｏｏｎ３ ＃ｎｉｎｔｅｎｄｏｓｗｉｔ
  ｈ ＃ｒｔ拡散希望 ｈｔｔｐｓ：／／ｔ．ｃｏ／ｒｃｔｓｔｌｋｅｎｃ",4],[3,"1586957457896591360",1667195116,"ブルボンメタバース ｈｔｔｐｓ：／／ｔ．ｃｏ／ｔｒｒ
  ｖｔｌｂｗ９",4]]]]

> select Media --query type:4
[[0,1667203613.28058,0.04248547554016113],[[[0],[["_id","UInt32"],["_key","ShortText"],["ctime","UInt32"],["desc","Text"],["type","UInt8"]]]]]
```

**Comment by genki** [comment] 2022-10-31 08:20
In addition, query by ':' for UInt32 column can select correct records as follows:

```
select Media --query ctime:1667087975
[[0,1667204234.936206,0.003123283386230469],[[[1],[["_id","UInt32"],["_key","ShortText"],["ctime","UInt32"],["desc","Text"],["type","UInt8"]],[1,"1586508073753268224",1667087975,"ａ ｔｒａｉｎ ｉｎ ｓｉｎｇａｐｏｒｅ ｗｉｔｈ ｗｉｎｄｏｗｓ
 ｔｈａｔ ａｕｔｏｍａｔｉｃａｌｌｙ ｂｌｉｎｄ ｗｈｅｎ ｐａｓｓｉｎｇ ｒｅｓｉ
  ｅｎｔｉａｌ ｂｌｏｃｋｓ． ｈｔｔｐｓ：／／ｔ．ｃｏ／ｓ０ｍｋｐｆｄｄｐｉ",4]]]]
```

I think it seems buggy behavior about UInt8.

**Comment by komainu8** [comment] 2022-11-07 07:22
Thank you for providing how to reproduce.
I could reproduce this problem in my environment.

This problem doesn't occur in the master.
In addition, if we use an older version than v9.0.9, this problem occurs.

This problem was fixed in https://github.com/groonga/groonga/commit/fc3c48407d5147f790aabaf098ba0da417a68386.

**Comment by genki** [comment] 2022-11-07 08:33
Thank you for confirming :)
I will try to update.

**Closed** 2022-11-07 08:33 UTC
